### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by KevinRiordan** [ciena/voltha-helm-charts#1]
I just started to go through the directions to deploy the helm charts on a k8s 1.14.1 cluster

cd volth-helm-charts
 should be 
cd voltha-helm-charts

**Comment by davidkbainbridge** [comment]
Thanks. The charts have now been officially moved to http://gerrit.opencord.org/voltha-helm-charts. So please you that as the repo. I suspect the same typo is there and I will queue that up for a change.

**Comment by KevinRiordan** [comment]
That link is broken. Where can I find the repo?

**Comment by davidkbainbridge** [comment]
Try https://gerrit.opencord.org/#/admin/projects/voltha-helm-charts (gerrit is funky, github is much easier imo.
